"""create formulas and formula_components tables

Revision ID: 37c9c7ad4335
Revises: eb1303f92dff
Create Date: 2026-10-03 18:24:28.862370

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '37c9c7ad4335'
down_revision: Union[str, Sequence[str], None] = 'eb1303f92dff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('formulas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'code', name='uq_formula_user_code')
    )
    op.create_index(op.f('ix_formulas_user_id'), 'formulas', ['user_id'], unique=False)
    op.create_table('formula_components',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('formula_id', sa.Integer(), nullable=False),
    sa.Column('component_name', sa.String(length=120), nullable=False),
    sa.Column('percentage', sa.Numeric(precision=6, scale=3), nullable=False),
    sa.Column('lab_l', sa.Numeric(precision=6, scale=3), nullable=True),
    sa.Column('lab_a', sa.Numeric(precision=6, scale=3), nullable=True),
    sa.Column('lab_b', sa.Numeric(precision=6, scale=3), nullable=True),
    sa.Column('delta_e', sa.Numeric(precision=6, scale=3), nullable=True),
    sa.Column('lab_source', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['formula_id'], ['formulas.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_formula_components_formula_id'), 'formula_components', ['formula_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_formula_components_formula_id'), table_name='formula_components')
    op.drop_table('formula_components')
    op.drop_index(op.f('ix_formulas_user_id'), table_name='formulas')
    op.drop_table('formulas')
    # ### end Alembic commands ###
